### ISSUE TITLE
Text on splash screen

### ISSUE THREAD

**Issue by milovanderlinden** [CodeForEindhoven/open311-hybrid#1]
When the app opens, the splash screen is shown. It is not completely clear that a user needs to push the splash screen to progress to the next screen.

**Comment by thijsalbers** [comment]
It indeed showed the splash screen for too long. Fixed in new version.

**Comment by thijsalbers** [comment]
It indeed showed the splash screen for too long. Fixed in new version.

**Comment by thijsalbers** [comment]
It indeed showed the splash screen for too long. Fixed in new version.

**Comment by thijsalbers** [comment]
It indeed showed the splash screen for too long. Fixed in new version.
