### ISSUE TITLE
Show response message

### ISSUE THREAD

**Issue by milovanderlinden** [CodeForEindhoven/open311-hybrid#2]
The app currently shows a message like "your message has been sent" but the back-end API provides a return message conform the open311-api specs. The return message should be shown. As the back-end is i18n aware, the accept-language header should be set when sending so the response will be in the correct language.

(See https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html on how to set accept-language)

**Comment by thijsalbers** [comment]
Fixed in version 1.0.0.2, will send out new build shortly.
